generator: admingenerator.generator.doctrine
params:
    model:              Admingenerator\DoctrineOrmDemoBundle\Entity\Category
    namespace_prefix:   Admingenerator
    i18n_catalog:       AdmingeneratorOrmDemoBundle
    concurrency_lock:   ~
    bundle_name:        DoctrineOrmDemoBundle
    pk_requirement:     ~
    fields: ~
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
builders:
    nested_list:
        indentation:
            field: name
        params:
            title: category.title.list
            display: ~
            actions:
                new: ~
            object_actions:
                edit: ~
                delete: ~
    excel:
        params: ~
        filename: ~
        filetype: ~
    filters:
        params:
            display: ~
    new:
        params:
            title: category.title.new
            display: ~
            actions:
                save: ~
                list: ~
    edit:
        params:
            title: category.title.edit
            display: ~
            actions:
                save: ~
                list: ~
    show:
        params:
            title: category.title.show
            display: ~
            actions:
                list: ~
                new: ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
