generator: admingenerator.generator.doctrine
params:
    model:              Admingenerator\DoctrineOrmDemoBundle\Entity\Post
    namespace_prefix:   Admingenerator
    i18n_catalog:       AdmingeneratorOrmDemoBundle
    concurrency_lock:   ~
    bundle_name:        DoctrineOrmDemoBundle
    pk_requirement: ~
    fields: ~
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
builders:
    list:
        params:
            title: post.title.list
            display: [ id, author, title, tags]
            scopes:
                "First Group":
                    "Empty":
                        default: true
                        filters: ~
                    "Published":
                        filters:
                            "isPublished": 1
            actions:
                new: ~
                excel: ~
            object_actions:
                edit: ~
                delete: ~
    excel:
        params:
            display: [id, author, title]
        filename: ~
        filetype: ~
    filters:
        params:
            display: []
    new:
        params:
            title: post.title.new
            display: ~
            actions:
                save: ~
                list: ~
    edit:
        params:
            title: post.title.edit
            display: ~
            actions:
                save: ~
                list: ~
    show:
        params:
            title: post.title.show
            display: ~
            actions:
                list: ~
                new: ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
