generator: admingenerator.generator.doctrine
params:
    model:              Admingenerator\DoctrineOrmDemoBundle\Entity\Post
    namespace_prefix:   Admingenerator
    i18n_catalog:       AdmingeneratorOrmDemoBundle
    concurrency_lock:   ~
    bundle_name:        DoctrineOrmDemoBundle
    pk_requirement: ~
    fields:
        author:
            filterable: 1
        category:
            filterable: 1
            filterOn: category.name
            credentials: CATEGORIZER
            formType: Admingenerator\FormExtensionsBundle\Form\Type\Select2EntityType
        isPublished:
            filterable: 1
            formType: Symfony\Component\Form\Extension\Core\Type\ChoiceType
        expirationDate:
            filterable: 1
        tags:
            formType: Admingenerator\FormExtensionsBundle\Form\Type\DoubleListEntityType
    actions:
        excel: 
            confirm: really?
    object_actions:
        delete: ~
        expire:
            icon: fa-calendar
            csrfProtected: true
            confirm: Do you really want to change expiration date?
            confirmModal: '#confirmObjectModalWithDate'
        simpleedit:
            confirm: Change title
    batch_actions:
        delete: ~
        expire:
            icon: fa-calendar
            csrfProtected: true
            confirm: Do you really want to change expiration date?
            confirmModal: '#confirmBatchModalWithDate'
builders:
    list:
        params:
            title: post.title.list
            display: [ author, title, tags, category, expirationDate ]
            # Customizing filters
            fields:
                isPublished:
                    addFormOptions:
                        required: false # Stupid sample, just to show how it works
            filters:
                - author
                - category
                - isPublished
            scopes:
                "First Group":
                    "Empty":
                        filters: ~
                    "John":
                        default: true
                        filters:
                            "author": "John Doe"
                "Second group":
                    "Published":
                        default: true
                        filters:
                            "isPublished": 1
            actions:
                new: ~
                excel: ~
            object_actions:
                edit: ~
                delete: ~
                expire: ~
                simpleedit: ~
            batch_actions:
                delete: ~
    excel:
        params:
            display: [id, author, title]
        filename: ~
        filetype: ~
    new:
        params:
            credentials: CONTRIBUTOR
            title: post.title.new
            display:
                - title
                - author
                - tags
                - thumbPath
                - category
                - content
                - expirationDate
                - isPublished
            actions:
                save: ~
                list:
                    confirm: Really cancel edit?
    edit:
        params:
            fields:
                author:
                    credentials: ROLE_USER
            title: post.title.edit
            display:
                - title
                - author
                - tags
                - thumbPath
                - category
                - content
                - expirationDate
            object_actions:
                show: ~
            actions:
                save:
                    confirm: Really save?
                list:
                    confirm: Really cancel edit?
    show:
        params:
            sidebar:
                post.box.first:
                    partial: AdmingeneratorDoctrineOrmDemoBundle:PostShow:firstBoxSidebar.html.twig
                post.box.second:
                    partial: AdmingeneratorDoctrineOrmDemoBundle:PostShow:secondBoxSidebar.html.twig
            title: post.title.show
            display: ~
            actions:
                list: ~
                new: ~
    actions:
        params:
            object_actions:
                delete: ~
                simpleedit: ~
                expire: ~
            batch_actions:
                delete: ~
                expire: ~
