generator: admingenerator.generator.doctrine
params:
    model:              Admingenerator\DoctrineOrmDemoBundle\Entity\Post
    namespace_prefix:   Admingenerator
    i18n_catalog:       AdmingeneratorOrmDemoBundle
    concurrency_lock:   ~
    bundle_name:        DoctrineOrmDemoBundle
    pk_requirement: ~
    fields:
        id:
            filterable: 1
        author:
            filterable: 1
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
builders:
    list:
        params:
            title: post.title.list
            display: [ id, author, title, tags]
            filters: ~
            scopes:
                "First Group":
                    "Empty":
                        default: true
                        filters: ~
                    "Published":
                        filters:
                            "isPublished": 1
                    "John":
                        filters:
                            "author": "John Doe"
            actions:
                new: ~
                excel: ~
            object_actions:
                edit: ~
                delete: ~
    excel:
        params:
            display: [id, author, title]
        filename: ~
        filetype: ~
    new:
        params:
            title: post.title.new
            display:
                - title
                - author
                - tags
                - thumbPath
                - category
                - content
            actions:
                save: ~
                list: ~
    edit:
        params:
            title: post.title.edit
            display:
                - title
                - author
                - tags
            object_actions:
                show: ~
            actions:
                save: ~
                list: ~
    show:
        params:
            sidebar:
                post.box.first:
                    partial: AdmingeneratorDoctrineOrmDemoBundle:PostShow:firstBoxSidebar.html.twig
                post.box.second:
                    partial: AdmingeneratorDoctrineOrmDemoBundle:PostShow:secondBoxSidebar.html.twig
            title: post.title.show
            display: ~
            actions:
                list: ~
                new: ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
