generator: admingenerator.generator.doctrine
params:
    model:              Admingenerator\DoctrineOrmDemoBundle\Entity\Tag
    namespace_prefix:   Admingenerator
    i18n_catalog:       AdmingeneratorOrmDemoBundle
    concurrency_lock:   ~
    bundle_name:        DoctrineOrmDemoBundle
    pk_requirement: ~
    fields:
        name:
            filterable: 1
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
builders:
    list:
        params:
            title: tag.title.list
            display: ~
            filters: ~
            filtersMode: top
            scopes:
                "Tag name":
                    "All tags":
                        default: true
                        filters: ~
                    "Amazing":
                        filters:
                            name: 'Amazing'
                    "Silly":
                        filters:
                            name: 'Silly'
                    "Sad":
                        filters:
                            name: 'Sad'
            actions:
                new: ~
            object_actions:
                edit: ~
                delete: ~
    excel:
        params: ~
        filename: ~
        filetype: ~
    filters:
        params:
            display:
                - name
    new:
        params:
            title: tag.title.new
            display: ~
            actions:
                save: ~
                list: ~
    edit:
        params:
            title: tag.title.edit
            display: ~
            actions:
                save: ~
                list: ~
    show:
        params:
            title: tag.title.show
            display: ~
            actions:
                list: ~
                new: ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
