vich_uploader:
    db_driver:  orm
    gaufrette:  false
    storage:    vich_uploader.storage.file_system
    mappings:
        doctrine_orm_blog_post_thumb:
            uri_prefix:           /doctrine_orm/blog_post/thumb
            upload_destination:   %kernel.root_dir%/../private/doctrine_orm/blog_post/thumb
            namer:                vich_uploader.namer_origname
            inject_on_load:       true
            delete_on_remove:     true
            delete_on_update:     true
        doctrine_odm_blog_post_thumb:
            uri_prefix:           /doctrine_odm/blog_post/thumb
            upload_destination:   %kernel.root_dir%/../private/doctrine_odm/blog_post/thumb
            namer:                vich_uploader.namer_origname
            inject_on_load:       true
            delete_on_remove:     true
            delete_on_update:     true
        propel_orm_blog_post_thumb:
            uri_prefix:           /propel_orm/blog_post/thumb
            upload_destination:   %kernel.root_dir%/../private/propel_orm/blog_post/thumb
            namer:                vich_uploader.namer_origname
            inject_on_load:       true
            delete_on_remove:     true
            delete_on_update:     true
